# Generated by Django 3.2.5 on 2022-03-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile_phone',
            field=models.CharField(max_length=32, null=True, verbose_name='手机号'),
        ),
    ]
