# Generated by Django 3.2.5 on 2022-03-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userinfo_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='repeat_password',
            field=models.CharField(max_length=32, verbose_name='重复密码'),
        ),
    ]
