# Generated by Django 3.2.5 on 2022-03-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pricepolicy_project_projectuser_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='repeat_password',
        ),
    ]
