# Generated by Django 3.2.5 on 2022-04-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_issuesreply_projectinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='name',
            field=models.CharField(help_text='文件/文件夹名', max_length=64, verbose_name='文件夹名称'),
        ),
    ]
