# Generated by Django 3.2.5 on 2022-08-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_filerepository_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.pricepolicy', verbose_name='价格策略'),
        ),
    ]
